name: flutter_application_1
description: "SmartSys Flutter App con autenticación"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Para peticiones HTTP a la API
  http: ^1.1.0

  socket_io_client: ^2.0.0

  # Para almacenamiento local (tokens de sesión)
  shared_preferences: ^2.2.2

  # Para mostrar mensajes toast
  fluttertoast: ^8.2.4

  # Para seleccionar imágenes de cámara/galería
  image_picker: ^1.0.7 # ← NUEVA LÍNEA AGREGADA

  # Iconos de Material Design
  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  intl_utils: ^2.8.5


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/avatars/
    - assets/images/banners/

# ✅ Configuración para cambiar el ícono de la app
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icono.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icono.png"
  windows:
    generate: true
    image_path: "assets/icono.png"
flutter_intl:
  enabled: true
