// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DtaBzFXqPlT8RDQsklLgf7oxTL9_Ly8',
    appId: '1:235729586108:web:86116fe38e5d2d8d5bcdb9',
    messagingSenderId: '235729586108',
    projectId: 'smartsys-app1',
    authDomain: 'smartsys-app1.firebaseapp.com',
    storageBucket: 'smartsys-app1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCipMyU80nUvPDccU321NPQtRqFoeKrjnk',
    appId: '1:235729586108:android:2a9135015a05d5965bcdb9',
    messagingSenderId: '235729586108',
    projectId: 'smartsys-app1',
    storageBucket: 'smartsys-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_nUCWtahIaxrAjxsnH25miwu-uaeuWgk',
    appId: '1:235729586108:ios:9b2dd93da0c8ff695bcdb9',
    messagingSenderId: '235729586108',
    projectId: 'smartsys-app1',
    storageBucket: 'smartsys-app1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_nUCWtahIaxrAjxsnH25miwu-uaeuWgk',
    appId: '1:235729586108:ios:9b2dd93da0c8ff695bcdb9',
    messagingSenderId: '235729586108',
    projectId: 'smartsys-app1',
    storageBucket: 'smartsys-app1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9DtaBzFXqPlT8RDQsklLgf7oxTL9_Ly8',
    appId: '1:235729586108:web:c7fb1361f6582c965bcdb9',
    messagingSenderId: '235729586108',
    projectId: 'smartsys-app1',
    authDomain: 'smartsys-app1.firebaseapp.com',
    storageBucket: 'smartsys-app1.firebasestorage.app',
  );
}
